FROM node:alpine
WORKDIR /usr/src/app
ENV API_URL=http://api-mock:8088
ENV PUBLIC_PATH=/familie/sykdom-i-familien/soknad/omsorgspenger
COPY . .
RUN CYPRESS_INSTALL_BINARY=0 npm ci
RUN npm run build
EXPOSE 8083
CMD ["npm", "run", "server-test"]
