# See .env for default ENV vars
version: '3.7'
services:
  api-mock:
    build: ../server
    environment:
      - "PORT=8088"
    ports:
      - 8088:8088
  web:
    build:
      context: ../
      dockerfile: Dockerfile.web-cypress
    ports:
      - 8083:8083
    depends_on:
      - api-mock
  e2e:
    build: .
    depends_on:
      - web
    environment:
      - CYPRESS_video=false
      - CYPRESS_baseUrl=http://web:8083
# Dersom debugging er nødvendig
#    working_dir: /e2e
#    volumes:
#      - ./:/e2e

