apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: omsorgspengesoknad
    namespace: default
    labels:
        team: {{team}}
spec:
    image: {{version}}
    port: 8080
    liveness:
        path: isalive
        initialDelay: 20
        timeout: 1
        periodSeconds: 5
        failureThreshold: 10
    readiness:
        path: isready
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    ingresses:
        - https://omsorgspengesoknad.nav.no
        - https://omsorgspengesoknad.nais.oera.no
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: true
        path: /metrics
    vault:
        enabled: false
    env:
        - name: APPRES_CMS_URL
          value: http://appres.nav.no
        - name: API_URL
          value: https://omsorgspengesoknad-api.nav.no
        - name: LOGIN_URL
          value: https://loginservice.nav.no/login?redirect=https://omsorgspengesoknad.nav.no/soknad/velkommen
        - name: HENT_BARN_FEATURE
          value: "on"
        - name: TOGGLE_LANGUAGE
          value: "on"
        - name: TOGGLE_FJERN_GRAD
          value: "off"

